[project]
name = "data-engineer-derec"
version = "0.2.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.2.2",
    "pytest>=8.3.5",
]

[dependency-groups]
dev = [
    "ruff>=0.11.6",
]
